2024-12-25 08:20:23.445 | ERROR    | __main__:main:40 - Telegram server says - Unauthorized
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000026F4B1AF2E0>
    │       └ <function run at 0x0000026F424E6F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000026F4B23A4D0>
           │      └ <function Runner.run at 0x0000026F4255A7A0>
           └ <asyncio.runners.Runner object at 0x0000026F4B2CE710>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:40> cb=[_run_until...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000026F42558400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000026F4B2CE710>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000026F4260F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000026F4255A160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000026F424AC7C0>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 38, in main
    await dp.start_polling(bot)  # Запуск опроса обновлений.
          │  │             └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
          │  └ <function Dispatcher.start_polling at 0x0000026F4B17D120>
          └ <Dispatcher '0x26f499e88d0'>

  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 551, in start_polling
    await asyncio.gather(*done)
          │       │       └ {<Task finished name='Task-2' coro=<Dispatcher._polling() done, defined at C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\s...
          │       └ <function gather at 0x0000026F425476A0>
          └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 340, in _polling
    user: User = await bot.me()
                       │   └ <function Bot.me at 0x0000026F4A115300>
                       └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\bot.py", line 366, in me
    self._me = await self.get_me()
    │    │           │    └ <function Bot.get_me at 0x0000026F4A1172E0>
    │    │           └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
    │    └ None
    └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\bot.py", line 1864, in get_me
    return await self(call, request_timeout=request_timeout)
                 │    │                     └ None
                 │    └ GetMe()
                 └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\bot.py", line 494, in __call__
    return await self.session(self, method, timeout=request_timeout)
                 │    │       │     │               └ None
                 │    │       │     └ GetMe()
                 │    │       └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
                 │    └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x0000026F4B2CEA10>
                 └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
           │    │                   │          │    └ GetMe()
           │    │                   │          └ <aiogram.client.bot.Bot object at 0x0000026F4B2CE950>
           │    │                   └ functools.partial(<bound method AiohttpSession.make_request of <aiogram.client.session.aiohttp.AiohttpSession object at 0x000...
           │    └ ~TelegramType
           └ <function cast at 0x0000026F4253A8E0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               │    └ <function BaseSession.check_response at 0x0000026F4A0EF920>
               └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x0000026F4B2CEA10>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\session\base.py", line 126, in check_response
    raise TelegramUnauthorizedError(method=method, message=description)
          │                                │               └ 'Unauthorized'
          │                                └ GetMe()
          └ <class 'aiogram.exceptions.TelegramUnauthorizedError'>

aiogram.exceptions.TelegramUnauthorizedError: Telegram server says - Unauthorized
2024-12-25 08:20:43.301 | ERROR    | __main__:main:40 - Telegram server says - Unauthorized
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000025DEDCEF2E0>
    │       └ <function run at 0x0000025DE5FE6F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000025DEDD7A3E0>
           │      └ <function Runner.run at 0x0000025DE605A7A0>
           └ <asyncio.runners.Runner object at 0x0000025DEEDDA750>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:40> cb=[_run_until...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000025DE6058400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000025DEEDDA750>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000025DE610F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000025DE605A160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000025DE5FAC7C0>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<_GatheringFu...result=[None]>)>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 38, in main
    await dp.start_polling(bot)  # Запуск опроса обновлений.
          │  │             └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
          │  └ <function Dispatcher.start_polling at 0x0000025DEDCC1120>
          └ <Dispatcher '0x25deeddac10'>

  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 551, in start_polling
    await asyncio.gather(*done)
          │       │       └ {<Task finished name='Task-2' coro=<Dispatcher._polling() done, defined at C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\s...
          │       └ <function gather at 0x0000025DE60476A0>
          └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 340, in _polling
    user: User = await bot.me()
                       │   └ <function Bot.me at 0x0000025DEDC25300>
                       └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\bot.py", line 366, in me
    self._me = await self.get_me()
    │    │           │    └ <function Bot.get_me at 0x0000025DEDC272E0>
    │    │           └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
    │    └ None
    └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\bot.py", line 1864, in get_me
    return await self(call, request_timeout=request_timeout)
                 │    │                     └ None
                 │    └ GetMe()
                 └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\bot.py", line 494, in __call__
    return await self.session(self, method, timeout=request_timeout)
                 │    │       │     │               └ None
                 │    │       │     └ GetMe()
                 │    │       └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
                 │    └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x0000025DEEDDAB50>
                 └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
           │    │                   │          │    └ GetMe()
           │    │                   │          └ <aiogram.client.bot.Bot object at 0x0000025DED4E8190>
           │    │                   └ functools.partial(<bound method AiohttpSession.make_request of <aiogram.client.session.aiohttp.AiohttpSession object at 0x000...
           │    └ ~TelegramType
           └ <function cast at 0x0000025DE603A8E0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               │    └ <function BaseSession.check_response at 0x0000025DEDC03920>
               └ <aiogram.client.session.aiohttp.AiohttpSession object at 0x0000025DEEDDAB50>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\client\session\base.py", line 126, in check_response
    raise TelegramUnauthorizedError(method=method, message=description)
          │                                │               └ 'Unauthorized'
          │                                └ GetMe()
          └ <class 'aiogram.exceptions.TelegramUnauthorizedError'>

aiogram.exceptions.TelegramUnauthorizedError: Telegram server says - Unauthorized
2024-12-25 08:25:28.250 | ERROR    | database.database:get_user_data:62 - no such table: authorized_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000027A7F50F2E0>
    │       └ <function run at 0x0000027A77786F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000027A7F59A3E0>
           │      └ <function Runner.run at 0x0000027A777FA7A0>
           └ <asyncio.runners.Runner object at 0x0000027A7F62A710>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000027A777F8400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000027A7F62A710>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000027A778BF740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000027A777FA160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000027A7774C7C0>
    └ <Handle <TaskStepMethWrapper object at 0x0000027A7C1B6B00>()>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x0000027A7C1B6B00>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x0000027A7C1B6B00>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000027A7C1B6B00>()>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,)}
                     │    │           │    └ Update(update_id=980912943, message=Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC...
                     │    │           └ <aiogram.client.bot.Bot object at 0x0000027A7F5A4950>
                     │    └ <function Dispatcher.feed_update at 0x0000027A7F4DCA40>
                     └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000027A7F4C74C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F638350>
                     └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912943, message=Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x0000027A7F6388D0>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912943, message=Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x0000027A7F638950>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912943, message=Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC...
                 └ <function TelegramEventObserver.trigger at 0x0000027A7F637CE0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912943, message=Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC...
                 └ <function CallableObject.call at 0x0000027A7F65DB20>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x27a7f62ad50'>>, Update(update_id=980912943, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │    │                           │                  └ Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │    │                           └ 'message'
                 │    └ <function Router.propagate_event at 0x0000027A7F4DC040>
                 └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000027A7F65D9E0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000027A7F4C74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F631110>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000027A7F4DC0E0>
                 └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                     │      │                           │                  └ Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │      │                           └ 'message'
                     │      └ <function Router.propagate_event at 0x0000027A7F4DC040>
                     └ <Router '0x27a7f5e0310'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000027A7F65DD00>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000027A7F4C74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F5E0390>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000027A7F4DC0E0>
                 └ <Router '0x27a7f5e0310'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                     │        │       └ Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │        └ <function TelegramEventObserver.trigger at 0x0000027A7F4C7600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F5E0390>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │             └ Message(message_id=786, date=datetime.datetime(2024, 12, 25, 5, 25, 27, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 └ <function CallableObject.call at 0x0000027A7F65DDA0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function start_bot_command at 0x0000027A7F5DEA20>, Message(message_id=786, date=datetime.datetime(2024, 12...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\launch_bot.py", line 53, in start_bot_command
    user_data_from_database = get_user_data(telegram_user_data["id"])
                              │             └ {'id': 1149708469, 'is_bot': False, 'first_name': 'Евгений', 'last_name': 'Вовк', 'username': 'rntainvaider', 'language_code'...
                              └ <function get_user_data at 0x0000027A7F5DCB80>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 52, in get_user_data
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x0000027A7F6B5E40>

sqlite3.OperationalError: no such table: authorized_user
2024-12-25 08:25:35.268 | ERROR    | database.database:get_user_data:62 - no such table: authorized_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000027A7F50F2E0>
    │       └ <function run at 0x0000027A77786F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000027A7F59A3E0>
           │      └ <function Runner.run at 0x0000027A777FA7A0>
           └ <asyncio.runners.Runner object at 0x0000027A7F62A710>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000027A777F8400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000027A7F62A710>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000027A778BF740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000027A777FA160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000027A7774C7C0>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,)}
                     │    │           │    └ Update(update_id=980912945, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x0000027A7F5A4950>
                     │    └ <function Dispatcher.feed_update at 0x0000027A7F4DCA40>
                     └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000027A7F4C74C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F638350>
                     └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912945, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x0000027A7F6388D0>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912945, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x0000027A7F638950>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912945, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x0000027A7F65FB00>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912945, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x0000027A7F65D9E0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x27a7f62ad50'>>, Update(update_id=980912945, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='4937960277512038833', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x0000027A7F4DC040>
                 └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960277512038833', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000027A7F65DD00>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000027A7F4C74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F631910>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000027A7F4DC0E0>
                 └ <Dispatcher '0x27a7f62ad50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                     │      │                           │                  └ CallbackQuery(id='4937960277512038833', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │      │                           └ 'callback_query'
                     │      └ <function Router.propagate_event at 0x0000027A7F4DC040>
                     └ <Router '0x27a7f5dbd50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960277512038833', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000027A7F65DDA0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000027A7F4C74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F602D50>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000027A7F4DC0E0>
                 └ <Router '0x27a7f5dbd50'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='4937960277512038833', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │        └ <function TelegramEventObserver.trigger at 0x0000027A7F4C7600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000027A7F602D50>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x27a7f62ad50'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000027A7F5A4950>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='4937960277512038833', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 └ <function CallableObject.call at 0x0000027A7F65DB20>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function back_to_main_menu at 0x0000027A7F60C2C0>, CallbackQuery(id='4937960277512038833', from_user=User(...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\personal_acount.py", line 184, in back_to_main_menu
    data_user = get_user_data(user_id)
                │             └ 1149708469
                └ <function get_user_data at 0x0000027A7F5DCB80>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 52, in get_user_data
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x0000027A7F9ADCC0>

sqlite3.OperationalError: no such table: authorized_user
2024-12-25 08:26:37.328 | ERROR    | database.database:get_user_data:62 - no such table: authorized_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x00000237DCEAF2E0>
    │       └ <function run at 0x00000237D4156F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x00000237DCF3A4D0>
           │      └ <function Runner.run at 0x00000237D41CA7A0>
           └ <asyncio.runners.Runner object at 0x00000237DCFCE990>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000237D41C8400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x00000237DCFCE990>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000237D428F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000237D41CA160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000237D411C7C0>
    └ <Handle <TaskStepMethWrapper object at 0x00000237DCF846D0>()>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x00000237DCF846D0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x00000237DCF846D0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000237DCF846D0>()>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,)}
                     │    │           │    └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                     │    │           └ <aiogram.client.bot.Bot object at 0x00000237DCFCEC90>
                     │    └ <function Dispatcher.feed_update at 0x00000237DCE80A40>
                     └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFDC550>
                     └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x00000237DCFDCAD0>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x00000237DCFDCB90>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ <function TelegramEventObserver.trigger at 0x00000237DCFDBCE0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ <function CallableObject.call at 0x00000237DCFF1B20>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x237dcf15990'>>, Update(update_id=980912946, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │    │                           │                  └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │    │                           └ 'message'
                 │    └ <function Router.propagate_event at 0x00000237DCE80040>
                 └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000237DCFF19E0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFD5390>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000237DCE800E0>
                 └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                     │      │                           │                  └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │      │                           └ 'message'
                     │      └ <function Router.propagate_event at 0x00000237DCE80040>
                     └ <Router '0x237dcf80290'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000237DCFF1D00>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCF80310>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000237DCE800E0>
                 └ <Router '0x237dcf80290'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                     │        │       └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │        └ <function TelegramEventObserver.trigger at 0x00000237DCE67600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCF80310>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │             └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 └ <function CallableObject.call at 0x00000237DCFF1DA0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function start_bot_command at 0x00000237DCF7EA20>, Message(message_id=788, date=datetime.datetime(2024, 12...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\launch_bot.py", line 53, in start_bot_command
    user_data_from_database = get_user_data(telegram_user_data["id"])
                              │             └ {'id': 1149708469, 'is_bot': False, 'first_name': 'Евгений', 'last_name': 'Вовк', 'username': 'rntainvaider', 'language_code'...
                              └ <function get_user_data at 0x00000237DCF7CB80>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 52, in get_user_data
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x00000237DD0555C0>

sqlite3.OperationalError: no such table: authorized_user
2024-12-25 08:26:37.619 | ERROR    | database.database:add_user_starting_the_bot:187 - UNIQUE constraint failed: not_authorized_user.id_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x00000237DCEAF2E0>
    │       └ <function run at 0x00000237D4156F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x00000237DCF3A4D0>
           │      └ <function Runner.run at 0x00000237D41CA7A0>
           └ <asyncio.runners.Runner object at 0x00000237DCFCE990>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000237D41C8400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x00000237DCFCE990>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000237D428F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000237D41CA160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000237D411C7C0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,)}
                     │    │           │    └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                     │    │           └ <aiogram.client.bot.Bot object at 0x00000237DCFCEC90>
                     │    └ <function Dispatcher.feed_update at 0x00000237DCE80A40>
                     └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFDC550>
                     └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x00000237DCFDCAD0>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x00000237DCFDCB90>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ <function TelegramEventObserver.trigger at 0x00000237DCFDBCE0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912946, message=Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC...
                 └ <function CallableObject.call at 0x00000237DCFF1B20>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x237dcf15990'>>, Update(update_id=980912946, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │    │                           │                  └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │    │                           └ 'message'
                 │    └ <function Router.propagate_event at 0x00000237DCE80040>
                 └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000237DCFF19E0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFD5390>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000237DCE800E0>
                 └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                     │      │                           │                  └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │      │                           └ 'message'
                     │      └ <function Router.propagate_event at 0x00000237DCE80040>
                     └ <Router '0x237dcf80290'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000237DCFF1D00>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCF80310>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000237DCE800E0>
                 └ <Router '0x237dcf80290'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                     │        │       └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │        └ <function TelegramEventObserver.trigger at 0x00000237DCE67600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCF80310>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │             └ Message(message_id=788, date=datetime.datetime(2024, 12, 25, 5, 26, 36, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 └ <function CallableObject.call at 0x00000237DCFF1DA0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function start_bot_command at 0x00000237DCF7EA20>, Message(message_id=788, date=datetime.datetime(2024, 12...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\launch_bot.py", line 60, in start_bot_command
    add_user_starting_the_bot(
    └ <function add_user_starting_the_bot at 0x00000237DCF7CFE0>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 153, in add_user_starting_the_bot
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x00000237DD130A40>

sqlite3.IntegrityError: UNIQUE constraint failed: not_authorized_user.id_user
2024-12-25 08:26:42.181 | ERROR    | database.database:get_user_data:62 - no such table: authorized_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x00000237DCEAF2E0>
    │       └ <function run at 0x00000237D4156F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x00000237DCF3A4D0>
           │      └ <function Runner.run at 0x00000237D41CA7A0>
           └ <asyncio.runners.Runner object at 0x00000237DCFCE990>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x00000237D41C8400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x00000237DCFCE990>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000237D428F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000237D41CA160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000237D411C7C0>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,)}
                     │    │           │    └ Update(update_id=980912948, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x00000237DCFCEC90>
                     │    └ <function Dispatcher.feed_update at 0x00000237DCE80A40>
                     └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFDC550>
                     └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912948, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x00000237DCFDCAD0>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912948, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x00000237DCFDCB90>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912948, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x00000237DCFF3D80>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912948, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x00000237DCFF19E0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x237dcf15990'>>, Update(update_id=980912948, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='4937960277650244428', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x00000237DCE80040>
                 └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960277650244428', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000237DCFF1D00>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFD5B50>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000237DCE800E0>
                 └ <Dispatcher '0x237dcf15990'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                     │      │                           │                  └ CallbackQuery(id='4937960277650244428', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │      │                           └ 'callback_query'
                     │      └ <function Router.propagate_event at 0x00000237DCE80040>
                     └ <Router '0x237dcf80110'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960277650244428', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x00000237DCFF1DA0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x00000237DCE674C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFA7190>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x00000237DCE800E0>
                 └ <Router '0x237dcf80110'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='4937960277650244428', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │        └ <function TelegramEventObserver.trigger at 0x00000237DCE67600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x00000237DCFA7190>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x237dcf15990'>, 'bots': (<aiogram.client.bot.Bot object at 0x00000237DCFCEC90>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='4937960277650244428', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 └ <function CallableObject.call at 0x00000237DCFF1B20>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function back_to_main_menu at 0x00000237DCFB02C0>, CallbackQuery(id='4937960277650244428', from_user=User(...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\personal_acount.py", line 184, in back_to_main_menu
    data_user = get_user_data(user_id)
                │             └ 1149708469
                └ <function get_user_data at 0x00000237DCF7CB80>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 52, in get_user_data
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x00000237DD355B40>

sqlite3.OperationalError: no such table: authorized_user
2024-12-25 08:28:14.757 | ERROR    | database.database:get_user_data:62 - no such table: authorized_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000014E9600F2E0>
    │       └ <function run at 0x0000014E8E316F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000014E9609A4D0>
           │      └ <function Runner.run at 0x0000014E8E38A7A0>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000014E8E388400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000014E8E43F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000014E8E38A160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000014E8E2DC7C0>
    └ <Handle <TaskStepMethWrapper object at 0x0000014E960F2500>()>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x0000014E960F2500>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x0000014E960F2500>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x0000014E960F2500>()>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,)}
                     │    │           │    └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                     │    │           └ <aiogram.client.bot.Bot object at 0x0000014E9612EB90>
                     │    └ <function Dispatcher.feed_update at 0x0000014E95FDCA40>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E9613C210>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x0000014E9613C790>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x0000014E9613C850>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ <function TelegramEventObserver.trigger at 0x0000014E9613BC40>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ <function CallableObject.call at 0x0000014E9615DA80>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x14e9612ef10'>>, Update(update_id=980912949, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │    │                           │                  └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │    │                           └ 'message'
                 │    └ <function Router.propagate_event at 0x0000014E95FDC040>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615D940>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E96134FD0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │      │                           │                  └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │      │                           └ 'message'
                     │      └ <function Router.propagate_event at 0x0000014E95FDC040>
                     └ <Router '0x14e960dbfd0'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615DC60>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E960E8110>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Router '0x14e960dbfd0'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │        │       └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │        └ <function TelegramEventObserver.trigger at 0x0000014E95FC7600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E960E8110>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 └ <function CallableObject.call at 0x0000014E9615DD00>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function start_bot_command at 0x0000014E960DE980>, Message(message_id=790, date=datetime.datetime(2024, 12...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\launch_bot.py", line 53, in start_bot_command
    user_data_from_database = get_user_data(telegram_user_data["id"])
                              │             └ {'id': 1149708469, 'is_bot': False, 'first_name': 'Евгений', 'last_name': 'Вовк', 'username': 'rntainvaider', 'language_code'...
                              └ <function get_user_data at 0x0000014E960DCAE0>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 52, in get_user_data
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x0000014E961B55C0>

sqlite3.OperationalError: no such table: authorized_user
2024-12-25 08:28:15.080 | ERROR    | database.database:add_user_starting_the_bot:187 - UNIQUE constraint failed: not_authorized_user.id_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000014E9600F2E0>
    │       └ <function run at 0x0000014E8E316F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000014E9609A4D0>
           │      └ <function Runner.run at 0x0000014E8E38A7A0>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000014E8E388400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000014E8E43F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000014E8E38A160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000014E8E2DC7C0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,)}
                     │    │           │    └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                     │    │           └ <aiogram.client.bot.Bot object at 0x0000014E9612EB90>
                     │    └ <function Dispatcher.feed_update at 0x0000014E95FDCA40>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E9613C210>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x0000014E9613C790>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x0000014E9613C850>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ <function TelegramEventObserver.trigger at 0x0000014E9613BC40>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912949, message=Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC...
                 └ <function CallableObject.call at 0x0000014E9615DA80>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x14e9612ef10'>>, Update(update_id=980912949, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │    │                           │                  └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │    │                           └ 'message'
                 │    └ <function Router.propagate_event at 0x0000014E95FDC040>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615D940>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E96134FD0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │      │                           │                  └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │      │                           └ 'message'
                     │      └ <function Router.propagate_event at 0x0000014E95FDC040>
                     └ <Router '0x14e960dbfd0'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615DC60>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E960E8110>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Router '0x14e960dbfd0'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │        │       └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                     │        └ <function TelegramEventObserver.trigger at 0x0000014E95FC7600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E960E8110>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ Message(message_id=790, date=datetime.datetime(2024, 12, 25, 5, 28, 13, tzinfo=TzInfo(UTC)), chat=Chat(id=1149708469, type='p...
                 └ <function CallableObject.call at 0x0000014E9615DD00>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function start_bot_command at 0x0000014E960DE980>, Message(message_id=790, date=datetime.datetime(2024, 12...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\launch_bot.py", line 60, in start_bot_command
    add_user_starting_the_bot(
    └ <function add_user_starting_the_bot at 0x0000014E960DCF40>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 153, in add_user_starting_the_bot
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x0000014E97260A40>

sqlite3.IntegrityError: UNIQUE constraint failed: not_authorized_user.id_user
2024-12-25 08:28:17.640 | ERROR    | database.database:get_user_data:62 - no such table: authorized_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000014E9600F2E0>
    │       └ <function run at 0x0000014E8E316F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000014E9609A4D0>
           │      └ <function Runner.run at 0x0000014E8E38A7A0>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000014E8E388400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000014E8E43F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000014E8E38A160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000014E8E2DC7C0>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,)}
                     │    │           │    └ Update(update_id=980912951, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x0000014E9612EB90>
                     │    └ <function Dispatcher.feed_update at 0x0000014E95FDCA40>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E9613C210>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912951, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x0000014E9613C790>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912951, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x0000014E9613C850>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912951, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x0000014E9615FCE0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912951, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x0000014E9615D940>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x14e9612ef10'>>, Update(update_id=980912951, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='4937960276367435588', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x0000014E95FDC040>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960276367435588', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615DC60>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E961357D0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │      │                           │                  └ CallbackQuery(id='4937960276367435588', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │      │                           └ 'callback_query'
                     │      └ <function Router.propagate_event at 0x0000014E95FDC040>
                     └ <Router '0x14e95a80150'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960276367435588', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615DD00>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E96107DD0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Router '0x14e95a80150'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='4937960276367435588', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │        └ <function TelegramEventObserver.trigger at 0x0000014E95FC7600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E96107DD0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='4937960276367435588', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 └ <function CallableObject.call at 0x0000014E96139300>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function back_to_main_menu at 0x0000014E96110220>, CallbackQuery(id='4937960276367435588', from_user=User(...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\personal_acount.py", line 184, in back_to_main_menu
    data_user = get_user_data(user_id)
                │             └ 1149708469
                └ <function get_user_data at 0x0000014E960DCAE0>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 52, in get_user_data
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x0000014E97486540>

sqlite3.OperationalError: no such table: authorized_user
2024-12-25 08:28:20.460 | ERROR    | database.database:get_user_data:62 - no such table: authorized_user
Traceback (most recent call last):

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py", line 44, in <module>
    asyncio.run(main())  # Запуск основного цикла бота.
    │       │   └ <function main at 0x0000014E9600F2E0>
    │       └ <function run at 0x0000014E8E316F20>
    └ <module 'asyncio' from 'D:\\Python\\Lib\\asyncio\\__init__.py'>

  File "D:\Python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x0000014E9609A4D0>
           │      └ <function Runner.run at 0x0000014E8E38A7A0>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at c:\Users\oito10\Desktop\Workout-Tracker\bot\run_bot.py:38> wait_for=<Futu...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x0000014E8E388400>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x0000014E960DB950>
  File "D:\Python\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000014E8E43F740>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000014E8E38A160>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "D:\Python\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000014E8E2DC7C0>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "D:\Python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=True>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=True>)>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
                     │    │           │    │         └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,)}
                     │    │           │    └ Update(update_id=980912953, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                     │    │           └ <aiogram.client.bot.Bot object at 0x0000014E9612EB90>
                     │    └ <function Dispatcher.feed_update at 0x0000014E95FDCA40>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
                     │    │      └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                     │    └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E9613C210>
                     └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912953, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.dispatcher.middlewares.user_context.UserContextMiddleware object at 0x0000014E9613C790>, functools...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912953, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ functools.partial(<aiogram.fsm.middleware.FSMContextMiddleware object at 0x0000014E9613C850>, <function TelegramEventObserver...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
                 │       │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │       └ Update(update_id=980912953, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function TelegramEventObserver.trigger at 0x0000014E96139620>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ Update(update_id=980912953, message=None, edited_message=None, channel_post=None, edited_channel_post=None, business_connecti...
                 └ <function CallableObject.call at 0x0000014E961394E0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<bound method Dispatcher._listen_update of <Dispatcher '0x14e9612ef10'>>, Update(update_id=980912953, messa...
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
                 │    │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │    │                           │                  └ CallbackQuery(id='4937960275075288405', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │    │                           └ 'callback_query'
                 │    └ <function Router.propagate_event at 0x0000014E95FDC040>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960275075288405', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615DDA0>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E961357D0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Dispatcher '0x14e9612ef10'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
                     │      │                           │                  │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │      │                           │                  └ CallbackQuery(id='4937960275075288405', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │      │                           └ 'callback_query'
                     │      └ <function Router.propagate_event at 0x0000014E95FDC040>
                     └ <Router '0x14e95a80150'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
                 │        │                     │               │           └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │        │                     │               └ CallbackQuery(id='4937960275075288405', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 │        │                     └ <function Router.propagate_event.<locals>._wrapped at 0x0000014E9615D940>
                 │        └ <function TelegramEventObserver.wrap_outer_middleware at 0x0000014E95FC74C0>
                 └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E96107DD0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
                 │    └ <function Router._propagate_event at 0x0000014E95FDC0E0>
                 └ <Router '0x14e95a80150'>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
                     │        │       │        └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                     │        │       └ CallbackQuery(id='4937960275075288405', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                     │        └ <function TelegramEventObserver.trigger at 0x0000014E95FC7600>
                     └ <aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x0000014E96107DD0>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
                 │             │      └ {'dispatcher': <Dispatcher '0x14e9612ef10'>, 'bots': (<aiogram.client.bot.Bot object at 0x0000014E9612EB90>,), 'bot': <aiogra...
                 │             └ CallbackQuery(id='4937960275075288405', from_user=User(id=1149708469, is_bot=False, first_name='Евгений', last_name='Вовк', u...
                 └ <function CallableObject.call at 0x0000014E9615DD00>
  File "C:\Users\oito10\Desktop\Workout-Tracker\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
                 └ functools.partial(<function back_to_main_menu at 0x0000014E96110220>, CallbackQuery(id='4937960275075288405', from_user=User(...

  File "c:\Users\oito10\Desktop\Workout-Tracker\bot\handlers\personal_acount.py", line 184, in back_to_main_menu
    data_user = get_user_data(user_id)
                │             └ 1149708469
                └ <function get_user_data at 0x0000014E960DCAE0>

> File "c:\Users\oito10\Desktop\Workout-Tracker\bot\database\database.py", line 52, in get_user_data
    cursor.execute(
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x0000014E97486A40>

sqlite3.OperationalError: no such table: authorized_user
